CGO_ENABLED=1 GOOS=android GOARCH=arm64 CC_FOR_TARGET=/home/aborjes3/Downloads/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android35-clang go build .


GOOS=android GOARCH=arm64 CGO_ENABLED=1 CC_FOR_TARGET=/home/aborjes3/Downloads/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android35-clang CGO_CFLAGS="--sysroot=/home/aborjes3/Downloads/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/sysroot" go build


CGO_ENABLED=1 GOOS=android GOARCH=arm64 CC=/home/aborjes3/Downloads/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android35-clang go build .

CGO_LDFLAGS


GOOS=android GOARCH=arm64 CGO_ENABLED=1 CC_FOR_TARGET=/home/aborjes3/Downloads/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android35-clang CGO_CFLAGS="--sysroot=/home/aborjes3/Downloads/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/sysroot"   CGO_LDFLAGS="--sysroot=/home/aborjes3/Downloads/android-ndk-r27c/toolchains/llvm/prebuilt/linux-x86_64/sysroot"  go build



CGO_ENABLED=1 GOOS=linux GOARCH=arm  go build .