
build-native:
	go build .

build-android-arm:
	bash build_android_arm.sh


build-android-arm64:
	bash build_android_arm64.sh

build-libpcap-arm:
	bash build_libpcap_arm.sh

build-libpcap-arm64:
	bash build_libpcap_arm64.sh
